source/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import login_view, logout_view, RegisterView, UserProfileView, UserPasswordChangeView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="registration"),
    path("<int:pk>/", UserProfileView.as_view(), name="user_profile"),
    path("change-password/", UserPasswordChangeView.as_view(), name="change_password")
]

source/hello/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

api_urlpattern = [
    path("v1/", include("api_v1.urls"))
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('webapp.urls')),
    path("account/", include("accounts.urls")),
    path("api/", include(api_urlpattern))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.views.photo import PhotoListView, PhotoDetailView, PhotoCreateView, PhotoUpdateView, PhotoDeleteView, PhotoTokenView
from webapp.views.album import AlbumDetailView, AlbumCreateView, AlbumUpdateView, AlbumDeleteView

from webapp.views.favorite import PhotoAddFavoriteView, PhotoDeleteFavoriteView

app_name = "webapp"

urlpatterns = [
    path("gallery/", PhotoListView.as_view(), name="index"),
    path('photo/<int:pk>/', PhotoDetailView.as_view(), name="photo_detail"),
    path("photo/create/", PhotoCreateView.as_view(), name="photo_create"),
    path("photo/update/<int:pk>/", PhotoUpdateView.as_view(), name="photo_update"),
    path("photo/delete/<int:pk>/", PhotoDeleteView.as_view(), name="photo_delete"),
    path("album/<int:pk>/", AlbumDetailView.as_view(), name="album_detail"),
    path("album/create/", AlbumCreateView.as_view(), name="album_create"),
    path("album/update/<int:pk>/", AlbumUpdateView.as_view(), name="album_update"),
    path("album/delete/<int:pk>/", AlbumDeleteView.as_view(), name="album_delete"),
    path("<token>/", PhotoTokenView.as_view(), name="token_view"),
    path("favorit/photo/add/<int:pk>/", PhotoAddFavoriteView.as_view(), name="favorite_photo_add"),
    path("favorit/photo/delete/<int:pk>", PhotoDeleteView.as_view(), name="favorite_photo_delete")
]

source/webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Photo(models.Model):
    photo = models.ImageField(upload_to='phote',
                              null=False,
                              blank=False,
                              verbose_name='Картинка')
    signature = models.CharField(max_length=200,
                                 null=False,
                                 blank=False,
                                 verbose_name='Подпись')
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        null=False,
        related_name='photos'
    )
    album = models.ForeignKey('webapp.Album',
                              on_delete=models.CASCADE,
                              null=True,
                              blank=True,
                              related_name='photos')
    private = models.BooleanField(default=False,
                                  verbose_name='Статус')
    token = models.UUIDField(null=True,
                             blank=True,
                             verbose_name='Токен')


class Album(models.Model):
    name = models.CharField(max_length=200,
                            null=False,
                            blank=False,
                            verbose_name='Название')
    description = models.TextField(max_length=2000,
                                   null=True,
                                   blank=True,
                                   verbose_name='Описание')
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        null=False,
        related_name='albums'
    )
    created_at = models.DateTimeField(auto_now_add=True)
    private = models.BooleanField(default=False, verbose_name='Статус')


class PhotoFavorites(models.Model):
    author = models.ForeignKey(get_user_model(), related_name="photo_favorite", on_delete=models.CASCADE)
    photo = models.ForeignKey("webapp.Photo", related_name="favorite", on_delete=models.CASCADE)

    class Meta:
        db_table = "photo_favorite"
        verbose_name = "Избранное фото"
        verbose_name_plural = "Избранные фото"

class AlbumFavorites(models.Model):
    author = models.ForeignKey(get_user_model(), related_name="album_favorite", on_delete=models.CASCADE)
    album = models.ForeignKey("webapp.Album", related_name="favorites", on_delete=models.CASCADE)

    class Meta:
        db_table = "album_favorite"
        verbose_name = "Избранный альбом"
        verbose_name_plural = "Избранные альбомы"

source/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm, UsernameField, UserChangeForm


User = get_user_model()

class UserCreationForm(UserCreationForm):
    email = forms.CharField(label="email", widget=forms.EmailInput, required=True)


    def clean(self):
        cleaned_data = super().clean()
        last_name = cleaned_data.get("last_name")
        first_name = cleaned_data.get("first_name")
        if not first_name:
            if not last_name:
                raise ValidationError("заполните хотя бы одно из полей: last_name, first_name")
        return cleaned_data

    class Meta(UserCreationForm.Meta):
        fields = ("username", "password1", "password2", "email", "first_name", "last_name")


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("email", "first_name", "last_name")


class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(label="Новый пароль", strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Подтвердите пароль", widget=forms.PasswordInput, strip=False)
    old_password = forms.CharField(label="Старый пароль", strip=False, widget=forms.PasswordInput)

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')
        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.instance.check_password(old_password):
            raise forms.ValidationError('Старый пароль неправильный!')
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()

        return user

    class Meta:
        model = User
        fields = ['password', 'password_confirm', 'old_password']

source/accounts/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model, update_session_auth_hash
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import CreateView, DetailView, ListView, UpdateView

from accounts.forms import UserCreationForm, UserUpdateForm, PasswordChangeForm

from webapp.models import Photo, Album

User = get_user_model()


class RegisterView(CreateView):
    model = User
    template_name = "registration.html"
    form_class = UserCreationForm

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if not next_url:
            next_url = self.request.POST.get('next')
        if not next_url:
            next_url = reverse('webapp:index')
        return next_url


def login_view(request):
    if request.user.is_authenticated:
        return redirect('webapp:project')
    context = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('webapp:project')
        else:
            context['has_error'] = True
    return render(request, 'login.html', context=context)


def logout_view(request):
    logout(request)
    return redirect('webapp:project')

class UserProfileView(LoginRequiredMixin, DetailView):
    model = get_user_model()
    template_name = "profile.html"
    paginate_related_by = 5
    paginate_related_orphans = 0
    context_object_name = "user_object"

    def get_context_data(self, **kwargs):
        photo = Photo.objects.filter(author=self.object)
        album = Album.objects.filter(author=self.object)
        kwargs["private_photo"] = photo.filter(private=True)
        kwargs["public_photo"] = photo.filter(private=False)
        kwargs['private_album'] = album.filter(private=True)
        kwargs['public_album'] = album.filter(private=False)
        return super(UserProfileView, self).get_context_data(**kwargs)


class UserPasswordChangeView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    template_name = 'user_password_change.html'
    form_class = PasswordChangeForm
    context_object_name = 'user_object'

    def form_valid(self, form):
        response = super().form_valid(form)
        update_session_auth_hash(self.request, self.object)
        return response

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse("accounts:user_profile", kwargs={"pk": self.request.user.pk})

source/accounts/templates/bases.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}List articles{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href=#>Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    {% block content %}{% endblock %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>
</html>

source/accounts/templates/login.html
{% extends 'base.html' %}

{% block title %}Вход{% endblock %}

{% block content %}
    <h1>Вход</h1>

    <form method="post" class="text-center ms-auto me-auto w-50">
        {% csrf_token %}
        {% if has_error == True %}
            <p class="text-danger">Неверное имя пользователя или пароль.</p>
        {% endif %}
        <div class="form-group">
            <label for="username" class="form-label">Имя пользователя:</label>
            <input type="text" name="username" id="username" class="form-control">
        </div>
        <div class="form-group">
            <label for="password" class="form-label">Пароль:</label>
            <input type="password" name="password" id="password" class="form-control">
        </div>

        <button class="mt-3 btn btn-primary" type="submit">Войти</button>
    </form>
{% endblock %}

source/accounts/templates/profile.html
{% extends "base.html" %}

{% block nav %}
    {% if user_object == user %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:change_password' %}">Изменить пароль</a>
        </li>
    {% endif %}
{% endblock nav %}

{% block content %}
    <h1>Профиль пользователя {{ user.username }}</h1>
    <p><strong>Почта: </strong>{{ user.email|default:"Не указана" }}</p>
    <p><strong>Дата рождения: </strong>{{ user.profile.birth_date|date:'d.m.Y'|default:"Не указана" }}</p>
    <p><strong>Фамилия: </strong>{{ user.last_name|default:"Не указана" }}</p>
    <p><strong>Имя: </strong>{{ user.first_name|default:"Не указанo" }}</p>

    <div style="display: flex">
        <div style="flex-direction: row; display: flex">
            <div class="blocks">
                <h4>Публичные Фотографии</h4>
                {% if public_photo %}
                    {% for photo in public_photo %}
                        {% if photo.photo %}
                            <img src="{{ photo.photo.url }}" width="150" height="151" alt="photo avatar">
                        {% endif %}
                        <p>{{ photo.signature }}</p>
                        {% if perms.webapp.change_photo or user == photo.author %}
                            <p><a href="{% url 'webapp:photo_update' photo.pk %}">Редактировать</a></p>
                        {% endif %}
                        {% if perms.webapp.delete_photo or user == photo.author %}
                            <p><a href="{% url 'webapp:photo_delete' photo.pk %}">Удалить</a></p>
                        {% endif %}
                    {% endfor %}
                {% else %}
                    <p>Отсутвуют</p>
                {% endif %}

            </div>
            <div class="blocks">
                <h4>Приватные Фотографии</h4>
                {% if private_photo %}
                    {% for photo in private_photo %}
                        {% if photo.photo %}
                            <img src="{{ photo.photo.url }}" width="150" height="151" alt="photo avatar">
                        {% endif %}
                        <p>{{ photo.signature }}</p>
                        {% if perms.webapp.change_photo or user == photo.author %}
                            <p><a href="{% url 'webapp:photo_update' photo.pk %}">Редактировать</a></p>
                        {% endif %}
                        {% if perms.webapp.delete_photo or user == photo.author %}
                            <p><a href="{% url 'webapp:photo_delete' photo.pk %}">Удалить</a></p>
                        {% endif %}
                    {% endfor %}
                {% else %}
                    <p>Отсутвуют</p>
                {% endif %}
            </div>
            <div class="blocks">
                <h4>Публичные альбомы Альбомы</h4>
                {% if public_album %}
                    {% for album in public_album %}
                        <p>Название: {{ album.name }}</p>
                        <p>Описание: {{ album.description }}</p>
                        {% if perms.webapp.change_album or user == album.author %}
                            <p><a href="{% url 'webapp:album_update' album.pk %}">Редактировать</a></p>
                        {% endif %}
                        {% if perms.webapp.delete_album or user == album.author %}
                            <p><a href="{% url 'webapp:album_delete' album.pk %}">Удалить</a></p>
                        {% endif %}
                    {% endfor %}
                {% else %}
                    <p>Отсутвуют</p>
                {% endif %}
            </div>
            <div class="blocks">
                <h4>Приватные Альбомы</h4>
                {% if private_album %}
                    {% for album in private_album %}
                        <p>Название: {{ album.name }}</p>
                        <p>Описание: {{ album.description }}</p>
                        {% if perms.webapp.change_album or user == album.author %}
                            <p><a href="{% url 'webapp:album_update' album.pk %}">Редактировать</a></p>
                        {% endif %}
                        {% if perms.webapp.delete_album or user == album.author %}
                            <p><a href="{% url 'webapp:album_delete' album.pk %}">Удалить</a></p>
                        {% endif %}
                    {% endfor %}
                {% else %}
                    <p>Отсутвуют</p>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock content %}

source/accounts/templates/registration.html
{% extends 'base.html' %}

{% block title %}Регистрация{% endblock %}

{% block content %}
    <h1>Регистрация</h1>
    <form method="post">
        {% include "partial/form.html"  with button_text="Зарегистрироваться" %}
    </form>
{% endblock %}

source/accounts/templates/update_profile.html
{% extends "base.html" %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include "partial/form.html" with fields_only=True %}
        {% include "partial/form.html" with fields_only=True form=profile_form %}
        <input type="submit" value="Сахранить" />
    </form>
{% endblock content %}

source/accounts/templates/user_password_change.html
{% extends 'base.html' %}


{% block title %}Смена пароля{% endblock %}


{% block nav %}
    <li class="nav-item">
        <a class="nav-link" href="{% url "accounts:user_profile" user.pk %}">Назад</a>
    </li>
{% endblock nav %}


{% block content %}

    <h1>Смена пароля</h1>

    <form method="POST">
        {% include 'partial/form.html' with button_text="Изменить" %}
    </form>

{% endblock %}