source/hello/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

api_urlpattern = [
    path("v1/", include("api_v1.urls"))
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('webapp.urls')),
    path("account/", include("accounts.urls")),
    path("api/", include(api_urlpattern))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.views.photo import PhotoListView, PhotoDetailView, PhotoCreateView, PhotoUpdateView, PhotoDeleteView, PhotoTokenView
from webapp.views.album import AlbumDetailView, AlbumCreateView, AlbumUpdateView, AlbumDeleteView

from webapp.views.favorite import PhotoAddFavoriteView, PhotoDeleteFavoriteView

app_name = "webapp"

urlpatterns = [
    path("gallery/", PhotoListView.as_view(), name="index"),
    path('photo/<int:pk>/', PhotoDetailView.as_view(), name="photo_detail"),
    path("photo/create/", PhotoCreateView.as_view(), name="photo_create"),
    path("photo/update/<int:pk>/", PhotoUpdateView.as_view(), name="photo_update"),
    path("photo/delete/<int:pk>/", PhotoDeleteView.as_view(), name="photo_delete"),
    path("album/<int:pk>/", AlbumDetailView.as_view(), name="album_detail"),
    path("album/create/", AlbumCreateView.as_view(), name="album_create"),
    path("album/update/<int:pk>/", AlbumUpdateView.as_view(), name="album_update"),
    path("album/delete/<int:pk>/", AlbumDeleteView.as_view(), name="album_delete"),
    path("<token>/", PhotoTokenView.as_view(), name="token_view"),
    path("favorit/photo/add/<int:pk>/", PhotoAddFavoriteView.as_view(), name="favorite_photo_add"),
    path("favorit/photo/delete/<int:pk>", PhotoDeleteView.as_view(), name="favorite_photo_delete")
]

source/webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Photo(models.Model):
    photo = models.ImageField(upload_to='phote',
                              null=False,
                              blank=False,
                              verbose_name='Картинка')
    signature = models.CharField(max_length=200,
                                 null=False,
                                 blank=False,
                                 verbose_name='Подпись')
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        null=False,
        related_name='photos'
    )
    album = models.ForeignKey('webapp.Album',
                              on_delete=models.CASCADE,
                              null=True,
                              blank=True,
                              related_name='photos')
    private = models.BooleanField(default=False,
                                  verbose_name='Статус')
    token = models.UUIDField(null=True,
                             blank=True,
                             verbose_name='Токен')


class Album(models.Model):
    name = models.CharField(max_length=200,
                            null=False,
                            blank=False,
                            verbose_name='Название')
    description = models.TextField(max_length=2000,
                                   null=True,
                                   blank=True,
                                   verbose_name='Описание')
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        null=False,
        related_name='albums'
    )
    created_at = models.DateTimeField(auto_now_add=True)
    private = models.BooleanField(default=False, verbose_name='Статус')


class PhotoFavorites(models.Model):
    author = models.ForeignKey(get_user_model(), related_name="photo_favorite", on_delete=models.CASCADE)
    photo = models.ForeignKey("webapp.Photo", related_name="favorite", on_delete=models.CASCADE)

    class Meta:
        db_table = "photo_favorite"
        verbose_name = "Избранное фото"
        verbose_name_plural = "Избранные фото"

class AlbumFavorites(models.Model):
    author = models.ForeignKey(get_user_model(), related_name="album_favorite", on_delete=models.CASCADE)
    album = models.ForeignKey("webapp.Album", related_name="favorites", on_delete=models.CASCADE)

    class Meta:
        db_table = "album_favorite"
        verbose_name = "Избранный альбом"
        verbose_name_plural = "Избранные альбомы"

source/webapp/forms.py
from django import forms

from webapp.models import Photo, Album, PhotoFavorites, AlbumFavorites

class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ('photo', 'signature', 'album', 'private',)
        labels = {
            "private": 'Сделать приватным'
        }

    def __init__(self, *args, **kwargs):
        albums = kwargs.pop('album')
        super().__init__(*args, **kwargs)
        self.fields['album'].queryset = albums


class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ('name', 'description', 'private')
        labels = {
            "private": 'Сделать приватным'
        }


class PhotoFavoriteForm(forms.ModelForm):
    class Meta:
        model = PhotoFavorites
        fields = ("author", "photo")

class AlbumFavoriteForm(forms.ModelForm):
    class Meta:
        model = AlbumFavorites
        fields = ("author", "album")

source/webapp/views/album.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView
from secrets import token_urlsafe

from webapp.models import Album, Photo
from webapp.forms import AlbumForm

class AlbumDetailView(LoginRequiredMixin, DetailView):
    template_name = 'album/detail.html'
    model = Album
    context_object_name = "album"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        photo = Photo.objects.filter(album=self.kwargs.get("pk"))
        context["photo_list"] = photo
        return context

class AlbumCreateView(LoginRequiredMixin, CreateView):
    template_name = "album/create.html"
    model = Album
    form_class = AlbumForm

    def form_valid(self, form):
        album = form.save(commit=False)
        album.author = self.request.user
        album.save()
        return redirect("webapp:index")


class AlbumUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = "album/update.html"
    model = Album
    form_class = AlbumForm
    permission_required = "webapp.change_album"

    def get_success_url(self):
        return reverse("webapp:album_detail", kwargs={"pk": self.object.pk})

    def has_permission(self):
        return self.get_object().author == self.request.user or super().has_permission()

class AlbumDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = "album/delete.html"
    model = Album
    permission_required = "webapp.delete_album"

    def post(self, request, *args, **kwargs):
        photos = Photo.objects.filter(album=self.kwargs.get("pk"))
        photos.delete()
        return super().delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse("webapp:index")

    def has_permission(self):
        return self.get_object().author == self.request.user or super().has_permission()

source/webapp/views/favorite.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView

from webapp.models import Photo, Album, PhotoFavorites, AlbumFavorites

from webapp.forms import PhotoFavoriteForm


class PhotoAddFavoriteView(LoginRequiredMixin, CreateView):
    model = PhotoFavorites
    template_name = "phote/create.html"
    form_class = PhotoFavoriteForm

    def post(self, request, *args, **kwargs):
        photo = get_object_or_404(Photo, pk=self.kwargs.get('pk'))
        if PhotoFavorites.objects.filter(photo=photo, author=self.request.user):
            pass
        else:
            PhotoFavorites.objects.create(photo=photo, author=self.request.user)
        return JsonResponse({"status": "add"})


class PhotoDeleteFavoriteView(LoginRequiredMixin, CreateView):
    model = PhotoFavorites
    template_name = "phote/create.html"
    form_class = PhotoFavorites

    def post(self, request, *args, **kwargs):
        photo = get_object_or_404(Photo, pk=self.kwargs.get('pk'))
        favorite = PhotoFavorites.objects.filter(photo=photo, author=self.request.user)
        if favorite:
            favorite.delete()
        return JsonResponse({"status": "delete"})

source/webapp/views/photo.py
import uuid

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from secrets import token_urlsafe

from webapp.models import Photo, Album
from webapp.forms import PhotoForm


class PhotoListView(LoginRequiredMixin, ListView):
    template_name = 'phote/index.html'
    model = Photo

    def get_context_data(self, *, object_list=None, **kwargs):
        kwargs["photos"] = Photo.objects.filter(private=False).order_by("-created_at")
        return kwargs


class PhotoDetailView(LoginRequiredMixin, DetailView):
    template_name = 'phote/detail.html'
    model = Photo
    context_object_name = "photo"


class PhotoCreateView(LoginRequiredMixin, CreateView):
    template_name = "phote/create.html"
    model = Photo
    form_class = PhotoForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['album'] = Album.objects.filter(author=self.request.user)
        return kwargs

    def form_valid(self, form):
        photo = form.save(commit=False)
        photo.author = self.request.user
        photo.token = uuid.uuid4()
        photo.save()
        return redirect("webapp:index")


class PhotoUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = "phote/update.html"
    model = Photo
    form_class = PhotoForm
    permission_required = 'webapp.change_photo'

    def get_success_url(self):
        return reverse("webapp:index")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['album'] = Album.objects.filter(author=self.request.user)
        return kwargs

    def has_permission(self):
        return self.get_object().author == self.request.user or super().has_permission()


class PhotoDeleteView(PermissionRequiredMixin, DeleteView):
    model = Photo
    template_name = "phote/delete.html"
    permission_required = "webapp.delete_photo"

    def post(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse("webapp:index")

    def has_permission(self):
        return self.get_object().author == self.request.user or super().has_permission()


class PhotoTokenView(View):
    def get(self, request, *args, **kwargs):
        context = {}
        token = kwargs.get("token")
        photo = Photo.objects.get(token=token)
        context["photo"] = photo
        return render(request, "phote/token_view.html", context)

source/webapp/templates/phote/create.html
{% extends "base.html" %}

{% block nav %}{% endblock %}
{% block content %}
    <h1>Создать Фото</h1>

    <form method="post" enctype="multipart/form-data">
        {% include "partial/form.html" with button_text="Создать" %}
    </form>

{% endblock %}>

source/webapp/templates/phote/delete.html
{% extends "base.html" %}

{% block content %}
    <form method="POST">
    {% csrf_token %}
        <h2>Вы действительно хотите удалить это фото</h2>
        <input type="submit" value="Да">
    </form>
    <a href="{% url "webapp:index" %}">Нет</a>
{% endblock %}

source/webapp/templates/phote/detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <h2>Фотография</h2>
    {% if photo.photo %}
        <img src="{{ photo.photo.url }}" alt="photo avatar">
    {% endif %}
    <p>Подпись: {{ photo.signature }}</p>
    <p>Автор: {{ photo.author }}</p>
    {% if user == photo.author %}
        <button type="button" id="buttons" onclick="onClick(event)" data-url="{% url "webapp:token_view" photo.token %}">Показать токен</button>
    {% endif %}

    <div id="tokens">

    </div>
    <p>Альбом: <a href="{% url 'webapp:album_detail' photo.author.pk %}">{{ photo.album.name }}</a></p>
    {% if perms.webapp.change_photo or user == photo.author %}
        <p><a href="{% url 'webapp:photo_update' photo.pk %}">Редактировать</a></p>
    {% endif %}
    {% if perms.webapp.delete_photo or user == photo.author %}
        <p><a href="{% url 'webapp:photo_delete' photo.pk %}">Удалить</a></p>
    {% endif %}

    {% block scripts %}
        <script src="{% static 'js/token.js' %}"></script>
    {% endblock %}
{% endblock %}

source/webapp/templates/phote/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    {% for photo in photos %}
        <div style="border: 2px solid black; max-width: 600px; margin-bottom: 20px; padding-left: 15px;border-radius: 33px">
            {% if photo.photo %}
                <img src="{{ photo.photo.url }}" width="200" height="201" alt="photo avatar">
            {% endif %}
            <p>Подпись: {{ photo.signature }}</p>
            <p>Автор: {{ photo.author }}</p>
            {% if photo.album.private == False %}
                <p>Альбом: <a href="{% url 'webapp:album_detail' photo.album.pk %}">{{ photo.album.name }}</a></p>
            {% endif %}
            <p><a href="{% url 'webapp:photo_detail' photo.pk %}">Подробно...</a></p>
            {% if perms.webapp.change_photo or user == photo.author %}
                <p><a href="{% url 'webapp:photo_update' photo.pk %}">Редактировать</a></p>
            {% endif %}
            {% if perms.webapp.delete_photo or user == photo.author %}
                <p><a href="{% url 'webapp:photo_delete' photo.pk %}">Удалить</a></p>
            {% endif %}
        {% if photo.favorite %}
            <button type="button" style="background: green" data-pk="{{ photo.pk }}" id="buttons-add" onclick="onClickPhoto(event)" data-url="{% url "webapp:favorite_photo_add" photo.pk %}">Добавить в избранное</button>
            {% else %}
            <button type="button" style="background: red" id="buttons-delete" onclick="onClickPhoto(event)" data-url="{% url "webapp:favorite_photo_delete" photo.pk %}">Удалить из избранных</button>
        {% endif %}

        </div>
    {% endfor %}
    {% block scripts %}
        <script src="{% static 'js/favorite.js' %}"></script>
    {% endblock %}
{% endblock content %}

source/webapp/templates/phote/token_view.html
{% extends "base.html" %}

{% block content %}
    <h2>Фотография</h2>
    {% if photo.photo %}
        <img src="{{ photo.photo.url }}" alt="photo avatar">
    {% endif %}
    <p>Подпись: {{ photo.signature }}</p>
    <p>Автор: {{ photo.author }}</p>
    <p>Альбом: {{ photo.album.name }}</p>

{% endblock %}

source/webapp/templates/phote/update.html
{% extends "base.html" %}

{% block content %}
    <h1>Редактировать Фото</h1>

    <form method="post" enctype="multipart/form-data">
        {% include "partial/form.html" with button_text="Редактировать" %}
    </form>

{% endblock %}